### ISSUE TITLE
Bump Version

### ISSUE THREAD

**Issue by lucasdiedrich** [Turgon37/docker-glpi#1]
Please bump the version to GLPI 9.2.1 and create one new image at docker hub.

Thanks.

**Comment by Turgon37** [comment]
I ensure you that it have been put in my todo list some weeks ago.
But I have to do theses things before:
* test the GLPI "migration" process (database concerns, eventually risk of data loss in docker volume)
* add new feature in same way like :
  * add authentifcated routes for http server (to allow authenticate connexion between fusioninventory agent and GLPI for example)
  * health check
  * metrology api

As you are the first person to ask me an upgrade, I will put this task upper in my todo list

**Comment by Turgon37** [comment]
I've just to upgrade GLPI to 9.2.1.
For now, I've not added new feature to the image itself, but I've seriously improved the image github build process.
This issue must be closed now, then I will continue the update by adding the above feature.

Feel free to make to make feedback on your upgrade succesness
