### ISSUE TITLE
crontab

### ISSUE THREAD

**Issue by Wolvverine** [Turgon37/docker-glpi#11]
GLPI use crontab, 
http://fusioninventory.org/documentation/fi4g/cron.html
add to  /etc/crontabs/root this :
```
  */5     *       *       *       *       run-parts /etc/periodic/5min
  *       *       *       *       *       /usr/bin/php5 /var/www/glpi/front/cron.php &>/dev/null
```

**Comment by Turgon37** [comment]
You are rights, initially I've setup a "homemade" cron task using a while and sleep command. But because it's not the aim of a docker file to run a such "batch" I've decided to add a variable to switch it off, but in facts, my code was wrong and the feature have never worked since.
