### ISSUE TITLE
graphviz for plugins (archires) is not instaled.

### ISSUE THREAD

**Issue by Wolvverine** [Turgon37/docker-glpi#12]
graphviz for plugins (archires) is not instaled.

**Comment by Turgon37** [comment]
Hello,
I've followed this guide http://wiki.glpi-project.org/doku.php?id=fr:plugins:archires_use and I have added the "graphviz" package in Dockerfile

I've pushed a development release with the name turgon37/glpi:develop-9.3-beta

Can you check if this release fill your needs ?

**Comment by Wolvverine** [comment]
It`s works perfectly.
