### ISSUE TITLE
Incomplete PHP installation. Required soap modules

### ISSUE THREAD

**Issue by Wolvverine** [Turgon37/docker-glpi#13]
for plugins Manufacturers Web Imports is error 
"Incomplete PHP installation. Required soap modules"

**Comment by Turgon37** [comment]
I've based my commit on this paper https://github.com/InfotelGLPI/manufacturersimports/blob/master/setup.php#L86 
So can you check if develop version work turgon37/glpi:develop-9.3-beta ?

**Comment by Wolvverine** [comment]
It`s work perfectly
