### ISSUE TITLE
9.3.0 use phpCAS extension

### ISSUE THREAD

**Issue by Wolvverine** [Turgon37/docker-glpi#19]
Alpine does not have this in the repository.

**Comment by czbadaro** [comment]
same problem here...

**Comment by Turgon37** [comment]
I agree with you too

```
CAS extension is not present
```
As I can see, the php-cas is not an extension but a simple library, on Debian a package exists with it https://packages.debian.org/jessie/all/php-cas/filelist. But on alpine, I can find any package like this one.
So I will think about it
