### ISSUE TITLE
issue in new nginx56 version - permission

### ISSUE THREAD

**Issue by Wolvverine** [Turgon37/docker-glpi#27]
Past update from old version:
Not write permission for www-data user in:
 /var/www/files/*
/var/www/config/config_db.php
(old user id 101)

Permision to write for www-data user for other glpi application file and directory in /war/www/*

**Comment by Turgon37** [comment]
I've also incorporate a fix for this issue, Please tell me is everythings is ok

**Comment by Wolvverine** [comment]
Is Ok.
