### ISSUE TITLE
issue in new nginx56 version - lost package

### ISSUE THREAD

**Issue by Wolvverine** [Turgon37/docker-glpi#28]
[Dockerfile_nginx-56.patch.txt](https://github.com/Turgon37/docker-glpi/files/3049020/Dockerfile_nginx-56.patch.txt)

**Comment by Turgon37** [comment]
A great thanks you for your contribution, I did not have took the time to really test the new 3.0.0 image with new php base. So I've incorporated your proposal, more others to me.

I've tested the new image on my environment it work fine.
Feel free to test on your side and give me a feedback.
