### ISSUE TITLE
Please update to the last glpi version

### ISSUE THREAD

**Issue by Elrondo46** [Turgon37/docker-glpi#29]
Please the 9.4 is out

**Comment by Turgon37** [comment]
Hello,
I've just to merge this PR #25 with my new image's version 3.0. The CI build related to this merge, has push the docker image with tag "nginx-56-9.4.3-latest". It contains the glpi version 4.3. (do not forget to check the changelog)

You can enjoy it

Feel free to open an issue if you have any issue with this version
