### ISSUE TITLE
How to make glpi wait mysql container ?

### ISSUE THREAD

**Issue by Elrondo46** [Turgon37/docker-glpi#34]
Please after reboot, error can't find mysql. Requires restart glpi container to make it functionnal

**Comment by skupfer** [comment]
Depends, I added an example in a pull request with a depends-on section for service v2.1. But the syntax changes later on.

example for docker-compose v3: https://dev.to/hugodias/wait-for-mongodb-to-start-on-docker-3h8b

**Comment by Turgon37** [comment]
Hello, you are right, this issue is not related to my image but to docker itself.
Thanks for your contribution :)
