### ISSUE TITLE
glpi 9.4.4 is out

### ISSUE THREAD

**Issue by Elrondo46** [Turgon37/docker-glpi#38]
Can you update it ?

**Comment by Turgon37** [comment]
Hello i've just to build the release version 9.4.4 https://cloud.docker.com/u/turgon37/repository/docker/turgon37/glpi you can test it now :)

**Comment by Elrondo46** [comment]
Access denied error

**Comment by Elrondo46** [comment]
Ok now it's good, don't understand why, restarted and fully functionnal. Thanks for this release

**Comment by Turgon37** [comment]
Have you any logs that could help to understand the error above ?

**Comment by Elrondo46** [comment]
I've understand the error, forgot in run line the image name, and putted it just the tag, the error is just between the chair and the keyboard, very sorry

turgon37/glpi:nginx-56-9.4.4-3.1.0 (GOOD)
turgon37/nginx-56-9.4.4-3.1.0 (BAD) (lol)

**Comment by Turgon37** [comment]
do not be bothered about this :)
But can the "Access denied error" error be produced by any of your loadbalancer ?

**Comment by Elrondo46** [comment]
no the cause of access denied, it's just because of an image bad request un docker hub. If you want to chat more about that, better to have it outiside of github issue zone (note, I'm french)

**Comment by Turgon37** [comment]
Ok I 've understand, this error had happen during the "docker pull" command :)
Thanks for your feedback
