### ISSUE TITLE
https in glpi

### ISSUE THREAD

**Issue by ghost** [Turgon37/docker-glpi#40]
Good, can it be configured to use port 443 with https certificate ??

**Comment by Turgon37** [comment]
Hello,
I understand your need with that question. But, like others image, I considers that is not to the responsibility of the application container to deal with https complexity. For example, it would require me to add parameters to configure certificate, ciphers and others few settings not directly related to GLPI.

I can redirect you to nextcloud recommendations https://github.com/docker-library/docs/blob/master/nextcloud/README.md#https---ssl-encryption and recommend you to use a reverse proxy like Traefik to handle certificates (with letsencrypt if you want).

**Comment by ghost** [comment]
but the application would have to work through https with which inside the glpi container you have to configure some certificates in nginx but then when you stop it they will be deleted again with which you should include ssl in the nginx of your build ???

I have already achieved it would be an improvement in any case

**Comment by Turgon37** [comment]
No, I dont think, this image (the nginx variant) aims to expose an http endpoint. By http I mean "http application" not "http protocol". If you want to expose glpi behind https to your customers, you have to put a https reverse proxy in front of this container. In fact the traffic between the reverse proxy and this image will remain in plain but I will be limited to localhost traffic only.

**Comment by ghost** [comment]
ok thanks.

**Comment by Turgon37** [comment]
I will update the readme to help people to understand this in the future :)
