### ISSUE TITLE
error in fusioninventory 

### ISSUE THREAD

**Issue by ghost** [Turgon37/docker-glpi#41]
This plugin requires GLPI> = 9.2 and <9.3 Uninstall

![image](https://user-images.githubusercontent.com/26000087/79895631-79b89980-8407-11ea-936e-9d8979eb84b8.png)

**Comment by Turgon37** [comment]
Hello, this is not an issue related to this repository. Please note that the fusion inventory plugin version written here https://github.com/Turgon37/docker-glpi#docker-compose-specific-configuration-examples is an "example of usage" not "the way" to use :)
The fusion inventory plugin has it's own lifecyle and you have to update the environment variable content according to new plugin's releases

So, the current version support glpi 9.5 https://github.com/fusioninventory/fusioninventory-for-glpi/blob/glpi9.4/setup.php#L52
and it is available with this url https://github.com/fusioninventory/fusioninventory-for-glpi/releases/download/glpi9.4%2B2.4/fusioninventory-9.4+2.4.tar.bz2

Feel free to update your docker-compose accordingly

Regards
