### ISSUE TITLE
alert Glpi cron

### ISSUE THREAD

**Issue by ghost** [Turgon37/docker-glpi#42]
when i go into fusioninventory i got an alert "GLPI cron is not running, see documentation" that can do something to fix it ???

**Comment by Turgon37** [comment]
Hello,
Effectively, I've removed the internal cron feature from this image. So you have to handle the cron scheduling outside of the running container. I've updated the readme to explain this.

https://github.com/Turgon37/docker-glpi/blob/develop/README.md#glpi-cronjob

Feel free to ask for help :)
