### ISSUE TITLE
upgrade to 9.5.1

### ISSUE THREAD

**Issue by ghost** [Turgon37/docker-glpi#53]
When I go to update I get the following renown:

updating software tables. This may take several minutes.

Rename "AuthLdap" itemtype to "AuthLDAP"
Rename "Crontask" itemtype to "CronTask"
Rename "InfoCom" itemtype to "Infocom"

where are those items, are the bd or are they files ??? I do not understand

**Comment by Turgon37** [comment]
Hello, I provide glpi application as a docker image but I'm not responsible of glpi upgrade process :)

Please refer to GLPI upgrade process available on their website

https://glpi-project.org/meet-glpi-9-5/
https://glpi-install.readthedocs.io/en/latest/update.html

Regards
