### ISSUE TITLE
GLPI version and compose Tag

### ISSUE THREAD

**Issue by t3cneo** [Turgon37/docker-glpi#56]
Hi,

using "image: turgon37/glpi:nginx-72-9.5.3-latest" in compose file gives me a manifest error
using "image: turgon37/glpi:nginx-72-latest" will setup glpi 9.5.1
using "image: turgon37/glpi" will setup glpi 9.3.3

Is your image up to date on docker hub?

**Comment by Turgon37** [comment]
Thanks to you, I've found an issue introduced by my own publish code :)
I've added the missing "latest" tags on image and updated accordingly the Readme

**Comment by t3cneo** [comment]
That was quick!
Thanks, I’ll give it a shot tomorrow. I really like your approach of GLPI on docker, on paper it seems to be the best out there, thanks for your hard work
